### ISSUE TITLE
Malicious - Codegate 2020

### ISSUE THREAD

**Issue by congtrung2k1** [balsn/ctf_writeup#10]
Hi there, I'm reading your ctf write-up, and I have a question at the sub_403F8C().

How could you see the pseudo code? I used IDA 7.2, and when I press F5, I saw "Please use ida (not ida64) to decompile the current file". It can be saw in ida x32 or ida x64.

Thanks !

**Comment by terrynini** [comment]
Are you sure that you were using the ida x32?
That should work without doubt

**Comment by congtrung2k1** [comment]
> Are you sure that you were using the ida x32?
> That should work without doubt

sorry, but it is ida 7.2 x32 ? i didn't bougth it,
 https://imgur.com/vAvzRz1
 https://imgur.com/iU4AeSR

**Comment by terrynini** [comment]
You didn't buy the decompiler plugin so it won't work
Try Ghidra, it's free
Also,the lack of decompilers won't stop you to solve challenges

**Comment by congtrung2k1** [comment]
> You didn't buy the decompiler plugin so it won't work
> Try Ghidra, it's free
> Also,the lack of decompilers won't stop you to solve challenges

Yeah, thanks
Maybe I use both of them to solve, just want to seeing a pseudo code to quickly understand.
Thanks alot
