### ISSUE TITLE
Google CTF Quals 2019 Malvertising Query

### ISSUE THREAD

**Issue by bhaviksec** [balsn/ctf_writeup#11]
https://balsn.tw/ctf_writeup/20190622-googlectfquals/#malvertising

I was able to beautify the javascript and was able to get android string. 

I am stuck in how do we get uHsdvEHFDwljZFhPyKxp.js file?

I got the below function but I am unable to determine how to execute the below function

```
var s = b("0x16", "%RuL");
var t = document[b("0x17", "jAUm")](b("0x18", "3hyK"));
/**
 * @return {undefined}
 */
t[b("0x19", "F#*Z")] = function() {
  try {
    var date = steg[b("0x1a", "OfTH")](t);
  } catch (v) {
  }
```

So would appreciate if you could help in steps in getting uHsdvEHFDwljZFhPyKxp.js file

**Comment by sces60107** [comment]
The website is still working https://malvertising.web.ctfcompetition.com/

First, open the site in your chrome or other browsers you are familiar with.
Set a breakpoint here.

![image](https://user-images.githubusercontent.com/14972618/76603627-40f3ed80-6548-11ea-86fb-1a902014a60e.png)

Then you can use those functions in console and get everything you need.


![image](https://user-images.githubusercontent.com/14972618/76603925-c7a8ca80-6548-11ea-94c2-3f6be4ef2189.png)


I hope these instructions can help you.

**Comment by bhaviksec** [comment]
Thanks a lot . Would try .

Could you share your email id if possible so that could learn and share few
tricks

**Comment by BookGin** [comment]
You can view our contact information on [Balsn's website](https://balsn.tw/).
