### ISSUE TITLE
How to dump memory sdsun challenge

### ISSUE THREAD

**Issue by RadCet** [balsn/ctf_writeup#2]
i'm still stuck at how to unpack this, i think i don't really understand elf format
can u show me a little more detail how i can unpack this
thank u so much

Ref: https://github.com/balsn/ctf_writeup/tree/master/20180411-hitbxctfqual#sdsun-sces60107-sasdf

**Comment by sces60107** [comment]
First, run the binary in `gdb` 

Then, use the command following. You will have the unpacked binary
`dump binary memory unpackfile start_pos end_pos`

**Comment by RadCet** [comment]
tks u so much for answer me, i know this feature in gdb but how i can dump it while it running ? did u attach to its process or set breakpoint ?

**Comment by sces60107** [comment]
I didn't set any breakpoint. 
Just run the binary in `gdb`.
After running a while, press `ctrl+c`. Now you can dump the memory.
