### ISSUE TITLE
About Wallbreaker Easy in 0CTF/TCTF 2019 Quals

### ISSUE THREAD

**Issue by SuperXiaoxiong** [balsn/ctf_writeup#5]
I try to bypass the open_basedir in your ways:
But the server just response without no error report
```
   array(7) {
  ["version"]=>
  int(1)
  ["type"]=>
  int(3)
  ["requestId"]=>
  int(1)
  ["contentLength"]=>
  int(8)
  ["paddingLength"]=>
  int(0)
  ["reserved"]=>
  int(0)
  ["content"]=>
  string(8) "
```
there is no problem using glob to get the php-fpm.sock
but when I can't read outside the open_basedir Using the method you say
I build the environment using https://hub.docker.com/r/richarvey/nginx-php-fpm

**Comment by w181496** [comment]
hi~
I'm the solver of this problem with fastcgi method.
It works on my docker environment (using richarvey/nginx-php-fpm).
I can read files outside the `open_basedir` with forged fastcgi request.

Maybe your environment settings have some problems (?

**Comment by SuperXiaoxiong** [comment]
Thanks,  I am wrong with FastCGI.
The real codes that  executes are in the auto_prepend_file file.
But seems there will be some surprise that I am dingging

**Comment by w181496** [comment]
what kind of the surprise😂🤔?

**Comment by SuperXiaoxiong** [comment]
Sorry for late because the apache vulnerability and I forget to check my email.
Have you try to bypass the disable_functions in the way using fastcgi ?
It's the post-credits scene you guys leave?

**Comment by w181496** [comment]
yes, it is possible to bypass disable_functions ;)
There are many secrets in the fastcgi

**Comment by BookGin** [comment]
Closed due to inactivity.
