### ISSUE TITLE
read l;read l

### ISSUE THREAD

**Issue by Imtinmin** [balsn/ctf_writeup#8]
https://balsn.tw/ctf_writeup/20190427-*ctf/#solution-2:-mkfifo-trick

```bash
$ cat pipe | /readflag |(read l;read l;echo "$(($l))\n" > pipe;cat) <dflag ((read 1;read l;echo .4(($1))\n. > pipe;cat) 
```
 是`read l`是`read line`意思吗，好像linux没有这个

**Comment by BookGin** [comment]
No, it's not `read line`.

[read](http://man7.org/linux/man-pages/man1/read.1p.html) is defined in POSIX standards. I think most shells should support this command.

**Comment by Imtinmin** [comment]
> No, it's not `read line`.
> 
> [read](http://man7.org/linux/man-pages/man1/read.1p.html) is defined in POSIX standards. I think most shells should support this command.

emmm,但是没有`read l`把
![image](https://user-images.githubusercontent.com/38977612/67187607-2005f100-f41d-11e9-8155-2c5de91f509c.png)

**Comment by BookGin** [comment]
I think your `read` is different from the [POSIX one](http://man7.org/linux/man-pages/man1/read.1p.html#EXAMPLES)?
`real foo` will read a string from stdin and it will be assigned to `$foo`.

**Comment by Imtinmin** [comment]
![image](https://user-images.githubusercontent.com/38977612/67667471-da12d500-f9a8-11e9-9656-f3492753039b.png)

**Comment by BookGin** [comment]
Oops. The correct command should be:

```sh
$ mkfifo pipe
$ cat pipe | ./readflag |(read l;read l;echo "$(($l))" > pipe;cat)
```

Thank you for that!

**Comment by Imtinmin** [comment]
Thank you very much!It can be worked.Now I just don't how to study fifo usage

**Comment by BookGin** [comment]
`cat pipe | ./readflag`:

1. read from pipe, and print it to stdin of ./readflag,
2. ./readflag will print the question to the next bunch of commands.

`(read l;read l;echo "$(($l))" > pipe;cat)`
1. read two lines from stdin
2. compute the result of line 2 `$(($l))` and print it to pipe
3. after printing the answer, `;cat` will read from ./readflag and thus print the flag

Once the answer is written to the pipe, `cat pipe` in the beginning will print the answer to `./readflag`, and it will print the flag. The last `;cat` will simply print it to stdout.

**Comment by Imtinmin** [comment]
emmm,if I want to see `$l`,how should I do

**Comment by BookGin** [comment]
I'm not sure I understand your question. You can just run `echo $l`.

**Comment by Imtinmin** [comment]
okok!I try
```zsh
cat pipe| ./readflag |(read l;read l;echo $l;echo $(($l))>pipe;cat)
```
can look at challenge,thank you very much.I will  improve myself.
